name: aoun_dev
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  provider: ^6.1.1
  get: ^4.6.6
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/A/1.png
    - assets/images/imagesForTest/1.png
    - assets/images/logo.png
  fonts:
    - family: Zain
      fonts:
        - asset: assets/fonts/Zain-Bold.ttf
        - asset: assets/fonts/Zain-ExtraBold.ttf
        - asset: assets/fonts/Zain-Light.ttf
        - asset: assets/fonts/Zain-ExtraLight.ttf
        - asset: assets/fonts/Zain-LightItalic.ttf
          style: italic
        - asset: assets/fonts/Zain-Italic.ttf
          style: italic
